### ISSUE TITLE
"test" drop should be confirmed automaticaly.

### ISSUE THREAD

**Issue by mohammadKarimi** [BlackBoot-io/Api#7]
a drop will be confirmed automatically if a drop has the following attributes:

- The drop should be marked as private (private: true)
- The name and description should include "test"

**Comment by MohammadMokhtarii** [comment]
The following questions would make things more clear if they were clarified
1-It would be better to have a flag or other preferred strategies rather than a "test"
2-As a result of auto-confirmation, should its metadata be stored in IPFS?
@mohammadKarimi

**Comment by mohammadKarimi** [comment]
it would be better to have a flag for test strategy rather than checking subject and other fields.
since this type of drop is for checking API integration, so we don't need to store any metadata in IPFS.
